/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TogetherWeCan;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class menuutamafundraiser extends javax.swing.JFrame {

    /**
     * Creates new form menuutamafundraiser
     */
    public menuutamafundraiser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuCampaigndonasi = new javax.swing.JMenuItem();
        jMenuprofile = new javax.swing.JMenuItem();
        jMenulogout = new javax.swing.JMenuItem();
        jMenuhelp2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu2.setText("Menu");

        jMenuCampaigndonasi.setText("Campaign Donasi");
        jMenuCampaigndonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCampaigndonasiActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuCampaigndonasi);

        jMenuprofile.setText("Profile");
        jMenuprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuprofileActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuprofile);

        jMenulogout.setText("Keluar");
        jMenulogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenulogoutActionPerformed(evt);
            }
        });
        jMenu2.add(jMenulogout);

        jMenuBar1.add(jMenu2);

        jMenuhelp2.setText("Help");
        jMenuBar1.add(jMenuhelp2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuprofileActionPerformed

    private void jMenuCampaigndonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCampaigndonasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCampaigndonasiActionPerformed

    private void jMenulogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenulogoutActionPerformed

    }//GEN-LAST:event_jMenulogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCampaigndonasi;
    private javax.swing.JMenu jMenuhelp2;
    private javax.swing.JMenuItem jMenulogout;
    private javax.swing.JMenuItem jMenuprofile;
    // End of variables declaration//GEN-END:variables
}
