/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TogetherWeCan;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class menuutamadonatur extends javax.swing.JFrame {

    /**
     * Creates new form menuutamadonatur
     */
    public menuutamadonatur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        jMenuBeranda = new javax.swing.JMenuItem();
        jMenuDonasi = new javax.swing.JMenuItem();
        jMenuGalangDana = new javax.swing.JMenuItem();
        jMenuProfile = new javax.swing.JMenuItem();
        jMenuLogout = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Menu.setText("Menu");

        jMenuBeranda.setText("Beranda");
        jMenuBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBerandaActionPerformed(evt);
            }
        });
        Menu.add(jMenuBeranda);

        jMenuDonasi.setText("Donasi");
        jMenuDonasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuDonasiActionPerformed(evt);
            }
        });
        Menu.add(jMenuDonasi);

        jMenuGalangDana.setText("Galang Dana");
        jMenuGalangDana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGalangDanaActionPerformed(evt);
            }
        });
        Menu.add(jMenuGalangDana);

        jMenuProfile.setText("Profile");
        jMenuProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProfileActionPerformed(evt);
            }
        });
        Menu.add(jMenuProfile);

        jMenuLogout.setText("Keluar");
        jMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLogoutActionPerformed(evt);
            }
        });
        Menu.add(jMenuLogout);

        jMenuBar1.add(Menu);

        Help.setText("Help");
        jMenuBar1.add(Help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBerandaActionPerformed
        // TODO add your handling code here:
        frberanda beranda = new frberanda();
        beranda.setLocationRelativeTo(this);
        beranda.setVisible(true);
        
    }//GEN-LAST:event_jMenuBerandaActionPerformed

    private void jMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLogoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Apakah Anda yakin ingin keluar?");
        this.setVisible(false);
        if(dialogResult == 0){
            //kondisi
            halamandepan hd = new halamandepan();
            hd.setVisible(true);
        }else{
            //kondisi
            menuutamadonatur mn = new menuutamadonatur();
            mn.setVisible(true);
        }
    }//GEN-LAST:event_jMenuLogoutActionPerformed

    private void jMenuProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProfileActionPerformed
        // TODO add your handling code here:
        frprofile profile = new frprofile();
        profile.setLocationRelativeTo(this);
        profile.setVisible(true);
    }//GEN-LAST:event_jMenuProfileActionPerformed

    private void jMenuDonasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuDonasiActionPerformed
        // TODO add your handling code here:
        frdonasi donasi = new frdonasi();
        donasi.setLocationRelativeTo(this);
        donasi.setVisible(true);
    }//GEN-LAST:event_jMenuDonasiActionPerformed

    private void jMenuGalangDanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGalangDanaActionPerformed
        this.dispose();
        frberanda_1 a = new frberanda_1();
        a.setVisible(true);
    }//GEN-LAST:event_jMenuGalangDanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutamadonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutamadonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutamadonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutamadonatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutamadonatur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Help;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBeranda;
    private javax.swing.JMenuItem jMenuDonasi;
    private javax.swing.JMenuItem jMenuGalangDana;
    private javax.swing.JMenuItem jMenuLogout;
    private javax.swing.JMenuItem jMenuProfile;
    // End of variables declaration//GEN-END:variables
}
